# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IZfaE5LjNCXgy46Eg2oBxu7K6wxWt2CB
"""

import cv2
from matplotlib import pyplot as plt
from google.colab.patches import cv2_imshow

# Imagem Fig0320(1)(top_left)
img1 = cv2.imread('Fig0320(1)(top_left).png', cv2.IMREAD_GRAYSCALE)
equ1 = cv2.equalizeHist(img1)
cv2_imshow(equ1)

# Imagem Fig0320(2)(2nd_from_top)
img2 = cv2.imread('Fig0320(2)(2nd_from_top).png', cv2.IMREAD_GRAYSCALE)
equ2 = cv2.equalizeHist(img2)
cv2_imshow(equ2)

# Imagem Fig0320(3)(third_from_top)
img3 = cv2.imread('Fig0320(3)(third_from_top).png', cv2.IMREAD_GRAYSCALE)
equ3 = cv2.equalizeHist(img3)
cv2_imshow(equ3)

# Imagem Fig0320(4)(bottom_left)
img4 = cv2.imread('Fig0320(4)(bottom_left).png', cv2.IMREAD_GRAYSCALE)
equ4 = cv2.equalizeHist(img4)
cv2_imshow(equ4)

# Imagem Fig0323(a)(mars_moon_phobos)
img5 = cv2.imread('Fig0323(a)(mars_moon_phobos).png', cv2.IMREAD_GRAYSCALE)
equ5 = cv2.equalizeHist(img5)
cv2_imshow(equ5)

# Imagem Fig0309(a)(washed_out_aerial_image)
img6 = cv2.imread('Fig0309(a)(washed_out_aerial_image).png', cv2.IMREAD_GRAYSCALE)
equ6 = cv2.equalizeHist(img6)
cv2_imshow(equ6)

# Imagem Fig0308(a)(fractured_spine)
img7 = cv2.imread('Fig0308(a)(fractured_spine).png', cv2.IMREAD_GRAYSCALE)
equ7 = cv2.equalizeHist(img7)
cv2_imshow(equ7)